[package]
name = "rusty_game"
version = "0.1.0"
edition = "2018"
authors = ["Spencer Nicol <spencern319@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.20.0"
rusty_audio = "1.2.1"
rusty_time = "0.11.3"
